### ISSUE TITLE
All progress actions can eventually break

### ISSUE THREAD

**Issue by daalta** [unitystation/unitystation#2898]
## Description

**(EDIT: This issue was originally about using mops, but seem to affect progress actions in general. See https://github.com/unitystation/unitystation/issues/2898#issuecomment-584093936)**

When attempting to use a mop on a floor tile nothing happens.

(EDIT: Seems to happen only occasionally)

### Detailed Bug Report
In the editor mops can be filled with water to clean floor tiles. This does not seem to work on our servers anymore.

The user "robotonic" from our Discord servers experienced the same issue. Last week mops worked alright, and I noticed the issue yesterday.

### Steps to Reproduce

1.  Grab a bucket
2.  Use the bucket on a water tank
3.  Switch hands, grab a mop
4. Use the mop on the bucket
5. Use the mop on a floor tile.

Expected beheviour: Character starts mopping the tile. (Works in the editor)
Actualy behaviour: Nothing happens. (Headless)

**Comment by daalta** [comment]
Oh, and by the way - janitors currently do not have a trash cart. This cannot stand.

**Comment by Bod9001** [comment]
it could be related to the Pickaxe breaking as well?

**Comment by DooblyNoobly** [comment]
mop works on AUS. Must of been because of server NRE

**Comment by daalta** [comment]
Today mops work fine again. Might be an issue that crops up over time or because of NREs.

**Comment by Bod9001** [comment]
I think it happens with all interactions, since I can't use a health analyser or open the locker, I can use the right click menu to manually trigger it though

**Comment by Bod9001** [comment]
odd I spawned in a locker and it worked fine with that

**Comment by Bod9001** [comment]
It looks like it's a client side issue after a hard reset on the server it was still happening

**Comment by DooblyNoobly** [comment]
no, progress bar code broke on the server

**Comment by DooblyNoobly** [comment]
oh yeah looks like the server error from last time it was up has screwed up the clients too
you will have to restart client

**Comment by daalta** [comment]
Still supposedly happens, though cleaning with fire extinguishers is an option!

**Comment by RedlineTriad** [comment]
Some interaction stuff broke on GER02 but it got fixed by hard restarting.
Might have something to do with this.
 #2995 might be related.

**Comment by fomalsd** [comment]
renamed since it's clearly something with progress actions in general

**Comment by fomalsd** [comment]
I think this was eventually fixed. will reopen if it occurs again

**Comment by AutumnNova** [comment]
Occurs for me with the client in build 4020 when I join a server
does not happen if I host one however
I have tried deleting and reinstalling, did not fix the issue
One interesting thing to note is that i can try and deconstruct multiple walls at once, making more than one progress bar display
[image](https://imgur.com/a/q5aLc5L)
