### ISSUE TITLE
Food processor sprite disappears when food is put through 

### ISSUE THREAD

**Issue by ArmenianUnion** [unitystation/unitystation#6173]
### Environment
- Game Version: 21030400
- OS Version: Mac OS Catalina

### Detailed description of bug

When putting any food into the food processor and activating it, upon completion the sprite for the processor will completely disappear when the food is dispensed leaving some to think the processor has disappeared all together.
### Steps to reproduce

1.  Aquire any type of food, (meat, cutlets etc)
2. Put it inside the processor and activate it.
3. Find that the processor sprite has disappeared completely when finished.
![Screenshot 2021-03-04 at 22 00 34](https://user-images.githubusercontent.com/80076755/110050107-1c8db400-7d4b-11eb-8bff-77a8dea04309.png)

**Comment by MaxIsJoe** [comment]
Fixed in #6214

**Comment by PetMudstone** [comment]
It's back. Tested on 21081300
![FoodProc](https://user-images.githubusercontent.com/38266309/129308993-4227574d-acfd-4450-850a-c2ed03e5a576.gif)

**Comment by PerfectTangent** [comment]
Reopening because it appears to still be happening.

**Comment by PetMudstone** [comment]
I can confirm this is still happening as of Staging 21092802. Oddly enough it seems to affect clients only and the sprite goes invisible when the processor starts processing this time. Hosts are completely unaffected.

Left is host and right is a client.
![FoodProc](https://user-images.githubusercontent.com/38266309/135025803-fb344853-e902-43d3-9999-825c273dd7f3.gif)

**Comment by MaxIsJoe** [comment]
this has been fixed
