### ISSUE TITLE
you bleed too quick when you remove a limb

### ISSUE THREAD

**Issue by Leander-0** [unitystation/unitystation#7583]
### Environment
- Game Version: Arch Linux
- OS Version: Staging 21101020

### Detailed description of bug

description in the title. i consider that 30 seconds to completely bleed out is too quick, im no medical expert on really how quick somoene bleeds out when his arm is chop off but i guess that 2 mins for someone too bleed out completely is considerably better mostly for gameplay reasons and balance.

https://user-images.githubusercontent.com/80334192/137561572-be868338-ae47-4dbb-9f1f-2a8f0da84ef6.mp4

### Steps to reproduce

1. chop limb
2. check blood

**Comment by JustinTrotter** [comment]
I'm noticing that blood is starting at 500cc. A quick google says it should be 5000cc. Quick bleedout is likely caused due to not having much blood in the first place rather than the rate of bleedout.

**Comment by VernaSaurus** [comment]
> I'm noticing that blood is starting at 500cc. A quick google says it should be 5000cc. Quick bleedout is likely caused due to not having much blood in the first place rather than the rate of bleedout.

That's... not true? On TG, the normal amount of blood is 560, and it regenerates at 0.25 blood per frame.

**Comment by JustinTrotter** [comment]
> That's... not true? On TG, the normal amount of blood is 560, and it regenerates at 0.25 blood per frame.

I find that number bizarre. But you're right, looking at it now, that is in fact how TG does it.

**Comment by PetMudstone** [comment]
I think the blood amount is "low" so that blood bags (capacity of 200u) can refill people.

**Comment by VernaSaurus** [comment]
> That's... not true? On TG, the normal amount of blood is 560, and it regenerates at 0.25 blood per frame.

Also, on the topic of blood regeneration, could whoever fixes the bleeding issue also add in blood regeneration? Currently, once you've lost blood, there's no way to get it back.

**Comment by corp-0** [comment]
> That's... not true? On TG, the normal amount of blood is 560, and it regenerates at 0.25 blood per frame.

except it is true. We use cc not u for blood. We fixed this issue with Mudstone some weeks ago but never commited it.

**Comment by PerfectTangent** [comment]
> Also, on the topic of blood regeneration, could whoever fixes the bleeding issue also add in blood regeneration? Currently, once you've lost blood, there's no way to get it back.

are bones not workin?

**Comment by VernaSaurus** [comment]
> are bones not workin?

not that I can tell

**Comment by VernaSaurus** [comment]
> except it is true. We use cc not u for blood. We fixed this issue with Mudstone some weeks ago but never committed it.

What's the conversion rate of cc to u?

**Comment by corp-0** [comment]
no one knows

**Comment by VernaSaurus** [comment]
> no one knows

then why do we use cc instead of u???

**Comment by JustinTrotter** [comment]
Probably because u is entirely arbitrary.

**Comment by JustinTrotter** [comment]
Anyway now that’s it’s clear that we are using cc. I think the solution is as easy as increasing the starting blood from 500 to 5000. That should make bleeding out take much longer.

I can do this later on tonight

**Comment by VernaSaurus** [comment]
> Anyway now that’s it’s clear that we are using cc. I think the solution is as easy as increasing the starting blood from 500 to 5000. That should make bleeding out take much longer.
> 
> I can do this later on tonight

actually on the discord we discussed this and decided that u is better than cc because:
1. a mixture of u and cc is absolutely not something we need
2. having an arbitrary measurement is better than a real measurement as if we have a real measurement people start getting very confused
3. cc is too specific (a beaker would hold exactly 236.588 cc instead of 50 u)

**Comment by corp-0** [comment]
What? Who decided u was better?

**Comment by VernaSaurus** [comment]
i thought that's what we settled on? did i misunderstand?

**Comment by PerfectTangent** [comment]
> Anyway now that’s it’s clear that we are using cc. I think the solution is as easy as increasing the starting blood from 500 to 5000. That should make bleeding out take much longer.
> 
> I can do this later on tonight

There's effectively no difference between raising the blood level and reducing the bleed rate.

We discussed in the health channel and Pet very reasonably argued that a lower number is better because it requires no conversion necessary to make blood packs actually do their job.

**Comment by JustinTrotter** [comment]
It looks like there’s a lot of confusion about expectations. Personally I don’t care one way or another on how to fix this. I just want to fix it. I understand that this was discussed in discord, was any reference or documentation written to account for these specifications?

**Comment by corp-0** [comment]
Basically in order to unify the unit measure, you would have to change it to "units* (eew) and rebalance all numbers in blood so it is a tenth of what it currently is. 

Another thing to consider is when blood is initialized it sets the amount to 500 from a hardcoded constant, which shouldn't be the case. Use the Blood data from the specie instead. We fixed this with Mudstone some weeks ago, ping me on discord later today if you can't find the thing.

**Comment by PetMudstone** [comment]
I don't think it's the best idea to try to rebalance blood loss and amounts right now, as Maxine hasn't finished up traumas nor the methods used to heal them.

**Comment by corp-0** [comment]
Sadly we have to. We need a playable thing now. We can adjust later. Changing numbers won't break the whole thing, it is just changing numbers.

**Comment by Leander-0** [comment]
Pls reopen this issue is back on Staging 21110300 as this 

https://user-images.githubusercontent.com/80334192/140237565-cd88a1be-2977-4726-9d78-ea17751dac57.mp4
